using System;
using System.Drawing;
using System.IO;

namespace Screenshot_Tool
{
    /// <summary>
    /// This class saves the screenshot at a given path, with a generated name and a selected datatype
    /// 
    /// Michael Hadorn
    /// </summary>
    public class SaveScreenshot
    {
        /// <summary>
        /// This method calls for the BuildSavePath method in order to create the path. After that it saves the screenshot
        /// </summary>
        /// <param name="name">autogenerated name</param>
        /// <param name="screenshot">the screenshot itself</param>
        /// <param name="path">storagepath</param>
        /// <param name="dataType">selected datatype for the image</param>
        public static void SaveScreenshotFromValues(string name, Bitmap screenshot, string path, string dataType)
        {
            try
            {
                path = BuildSavePath(path, name, dataType);
                screenshot.Save(path, ConvertImageFormat.ParseImageFormat(dataType));
                UserFeedback.ShowSuccess(name, path);
            }
            catch (Exception)
            {
                UserFeedback.ShowError();
            }
        }
        /// <summary>
        /// This method creats the path in order to save the image. 
        /// </summary>
        /// <param name="savePath">selected path from the user</param>
        /// <param name="name">name of the screenshot</param>
        /// <param name="dataType">datatype of the screenshot</param>
        /// <returns>the combined path</returns>
        public static string BuildSavePath(string savePath, string name, string dataType)
        {
            string fileName = name + "." + dataType.ToLower();
            string fullPath = Path.Combine(savePath, fileName);
            return fullPath;
        }
    }
}